name: On pull request opened

on:
    pull_request:
        branches: [ "main" ]

jobs:
    lint:
        name: Lint
        uses: ./.github/workflows/lint.yml

    test:
        name: Test
        needs: lint
        uses: ./.github/workflows/test.yml
        # secrets:
        #     JWT_SECRET: ${{ secrets.JWT_SECRET }}
        #     TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        #     DATABASE_URL: ${{ secrets.DATABASE_URL }}
        #     POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        #     POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        #     POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}